# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_O7an7uP3vB7jYqawXvPjyS5gNTUfBaw
"""

from flask import Flask, request, jsonify
import pickle
import pandas as pd

app = Flask(__name__)

# Load model at startup
with open("house_model.pkl", "rb") as f:
    model = pickle.load(f)

@app.route("/")
def home():
    return "House Price Prediction API is running!"


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "healthy"}), 200


@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()

        # Convert JSON input to DataFrame
        df = pd.DataFrame([data])

        # Predict
        prediction = model.predict(df)

        return jsonify({
            "prediction": prediction.tolist()
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 400


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)